"""Knowledge retrieve tool — builtin tool for KnowledgeBaseBrick (v1.0.0).

The `retrieve` tool lets the LLM actively query an external knowledge
base (KB) for relevant context chunks.  Registered as a CapBus builtin
when KnowledgeBaseBrick is active.

Design parallel to ``bricks/memory/tools.py``:
  - ``recall`` → searches agent's own memory (sessions, preferences, facts)
  - ``retrieve`` → searches an external KB (domain documents, reference files)

Semantic separation:
  - ``recall`` is introspective ("what has the agent learned about *this user*?")
  - ``retrieve`` is extrospective ("what does the KB say about *this topic*?")

Both expose a ``tool_definition`` property so ``CapBus.list_tool_definitions``
discovers them automatically via the builtins channel.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any


class RetrieveTool:
    """Builtin tool that lets the LLM query an external knowledge base.

    Registered on CapBus when KnowledgeBaseBrick is assembled.  The LLM
    calls ``retrieve(query, top_k)`` to fetch relevant document chunks
    from the pre-built KB index.

    Unlike ``RecallTool`` (which holds a ``MemoryBrick`` reference),
    ``RetrieveTool`` holds a plain callable — the retrieve function
    generated into ``src/<package>/knowledge_base.py`` at hatch time.
    This decoupling lets ``agenthatch-core`` stay framework-agnostic
    while each generated agent carries its own LLM-inferred retrieval
    strategy (query templates, integration pattern, etc.).
    """

    description = (
        "Retrieve relevant knowledge chunks from the agent's external "
        "knowledge base. Use this when the user asks about topics that "
        "the KB may cover. Always cite the source file in the answer."
    )

    schema: dict[str, Any] = {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": (
                    "Natural-language search query.  Use one of the "
                    "QUERY_TEMPLATES for best results."
                ),
            },
            "top_k": {
                "type": "integer",
                "description": (
                    "Maximum number of chunks to return.  "
                    "Omit to use the agent's configured default."
                ),
            },
        },
        "required": ["query"],
    }

    def __init__(
        self,
        retrieve_fn: Callable[..., Any] | None = None,
        *,
        description: str | None = None,
    ):
        """Initialize with a callable retrieve function.

        Args:
            retrieve_fn: The retrieve function generated by
                ``knowledge_base.py.j2``.  Signature: ``(query, top_k)``
                → ``list[dict]``.  May be ``None`` during graceful
                degradation (KB index missing); calls return empty list.
            description: Optional override for the tool description.
        """
        self._retrieve_fn = retrieve_fn
        if description is not None:
            self.description = description

    def execute(self, query: str, top_k: int | None = None) -> str:
        """Execute a KB retrieve query.

        Args:
            query: Natural language search query.
            top_k: Maximum number of chunks.  When ``None`` (the
                default), the call is forwarded to the generated
                ``retrieve()`` function which uses its own LLM-inferred
                ``MAX_RESULTS_PER_QUERY`` default.  When provided,
                clamped to 1-10 to guard against unreasonable LLM
                values.

        Returns:
            Formatted chunks as a string for the LLM.  Empty list
            scenarios are surfaced honestly so the LLM can fall back
            per ``FALLBACK_WHEN_NO_MATCH`` strategy.
        """
        if self._retrieve_fn is None:
            return "Knowledge base is not available."

        try:
            # v1.0.1 (M3): When LLM omits top_k, pass through so
            # retrieve() applies its own MAX_RESULTS_PER_QUERY default
            # (LLM-inferred per skill).  Previously we hardcoded 5,
            # silently overriding the per-skill configured default.
            if top_k is None:
                chunks = self._retrieve_fn(query)
            else:
                chunks = self._retrieve_fn(
                    query, top_k=min(max(top_k, 1), 10)
                )
        except Exception as e:
            return f"Knowledge base retrieve failed: {e}"

        # v1.0.1 (R3-M9): Validate the retrieve_fn contract before
        # iterating.  The generated ``retrieve()`` is documented to
        # return ``list[dict]``, but a tampered/misconfigured function
        # could return ``None`` (no return), a single dict (mistakenly
        # wrapped), or a string.  Previously a ``None`` return would
        # pass ``if not chunks`` and emit the "no matching chunks"
        # message — but a dict return would iterate over keys (strings),
        # producing garbage like ``[1] source=k chunk=0 heading=...``
        # for each dict key.  Coerce known bad shapes; surface a clear
        # error for genuinely unexpected types so users can spot the
        # misconfiguration instead of getting silent garbage.
        if chunks is None:
            return (
                "No matching chunks found in the knowledge base. "
                "Inform the user that the KB lacks this information."
            )
        if isinstance(chunks, dict):
            # Single dict — wrap as single-element list per the
            # documented contract's most-likely intent.
            chunks = [chunks]
        if not isinstance(chunks, list):
            return (
                f"Knowledge base retrieve returned unexpected type "
                f"{type(chunks).__name__} (expected list). "
                f"This indicates a misconfiguration in the generated "
                f"knowledge_base.py module — please re-run hatch."
            )

        if not chunks:
            return (
                "No matching chunks found in the knowledge base. "
                "Inform the user that the KB lacks this information."
            )

        # Format chunks into a single string block
        parts: list[str] = []
        for i, c in enumerate(chunks, 1):
            source = c.get("source", "unknown")
            idx = c.get("chunk_index", 0)
            heading = c.get("heading", "")
            score = c.get("score", 0.0)
            content = c.get("content", "")

            header = f"[{i}] source={source} chunk={idx}"
            if heading:
                header += f" heading={heading}"
            header += f" score={score}"
            parts.append(f"{header}\n{content}")
        # v1.0.1 (R4-V7): Use ``*** chunk boundary ***`` instead of bare
        # ``---`` to separate chunks.  Markdown spec treats a line of
        # ``---`` (3+ hyphens) as a thematic break / horizontal rule, so
        # when the LLM echoes retrieve results verbatim into its response,
        # the TUI's Markdown renderer draws an unexpected horizontal line
        # across the answer.  ``*** chunk boundary ***`` is plain text
        # (not a Markdown construct) and visually distinct.
        return "\n\n*** chunk boundary ***\n\n".join(parts)

    @property
    def tool_definition(self) -> Any:
        """Return the tool definition for CapBus registration."""
        from agenthatch_core.tools.bus import ToolDefinition
        return ToolDefinition(
            function={
                "name": "retrieve",
                "description": self.description,
                "parameters": self.schema,
            }
        )


def retrieve_tool(
    retrieve_fn: Callable[..., Any] | None = None,
    *,
    description: str | None = None,
) -> RetrieveTool:
    """Factory function for creating a RetrieveTool instance.

    Args:
        retrieve_fn: The retrieve function from the generated
            ``knowledge_base`` module.  May be ``None`` for graceful
            degradation paths.
        description: Optional override for the tool description.

    Returns:
        A RetrieveTool instance ready for CapBus registration.
    """
    return RetrieveTool(retrieve_fn=retrieve_fn, description=description)
