"""BrickManifest — compile-time chassis decomposition descriptor.

Level 0 — describes what bricks an agent needs.  Generated by the
hatch pipeline and consumed by AHCoreAgent.__init__ to assemble the
right runtime components (or null stubs for disabled features).

v0.8: Sandbox is always enabled — all agents execute tools as direct
subprocess (no Docker sandbox). SandboxTier remains as a sentinel for
backward compatibility but all agents use the same direct execution model.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class LoopKind(str, Enum):
    """Loop engine selection."""
    DIRECT = "direct"           # single-turn, no tool loop
    CONVERSATION = "conversation"  # multi-turn with tool loop
    PLAN_GUIDED = "plan_guided"    # PlanLayer + ConversationLoop


# v0.8: SandboxTier kept as sentinel for backward compatibility.
# All agents use the same direct-subprocess execution model.
# STANDARD and EXTENDED tiers map to the same whitelist as NONE.
class SandboxTier(str, Enum):
    """Execution tier (v0.8: all tiers equivalent — direct execution always)."""
    NONE = "none"
    STANDARD = "standard"
    EXTENDED = "extended"


@dataclass
class BrickManifest:
    """Compile-time descriptor for runtime brick assembly.

    Generated by classify_skill() during hatch Phase 2.5.
    Consumed by AHCoreAgent.__init__ to enable/disable bricks.

    v0.8: sandbox is always enabled (direct subprocess execution).
    sandbox field defaults to NONE but Sandbox() is always instantiated.
    """

    loop_engine: LoopKind = LoopKind.CONVERSATION

    # v0.8: sandbox always enabled — agents execute tools as direct subprocess
    sandbox: str = "none"

    # Optional bricks — None means "not needed, use null stub"
    capbus: bool = True
    hooks: bool = True
    guard: Any = None           # OutputGuard instance or None
    credential_vault: bool = False
    file_processor: bool = False

    # Archetype metadata
    archetype: str = "multi-step"  # SkillArchetype value as string
    archetype_confidence: float = 1.0

    # v0.7: guard_active — skip OutputGuard.validate() for prompt-only skills
    guard_active: bool = False

    # v0.7.6: memory — enable persistent MemoryBrick (default-on, opt-out)
    memory: bool = True

    # v0.9.7: task_complete — injected as a virtual tool so the LLM
    # can signal completion.  Set False for interactive REPL agents
    # where the user controls when the session ends.
    task_complete_enabled: bool = True
