"""BrickManifest — compile-time chassis decomposition descriptor.

Level 0 — describes what bricks an agent needs.  Generated by the
hatch pipeline and consumed by AHCoreAgent.__init__ to assemble the
right runtime components (or null stubs for disabled features).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class LoopKind(str, Enum):
    """Loop engine selection."""
    DIRECT = "direct"           # single-turn, no tool loop
    CONVERSATION = "conversation"  # multi-turn with tool loop
    PLAN_GUIDED = "plan_guided"    # PlanLayer + ConversationLoop


class SandboxTier(str, Enum):
    """Sandbox isolation level."""
    NONE = "none"           # no sandbox (prompt-only skills)
    STANDARD = "standard"   # builtin whitelist (python3, bash, etc.)
    EXTENDED = "extended"   # standard + user-configured extras


@dataclass
class BrickManifest:
    """Compile-time descriptor for runtime brick assembly.

    Generated by classify_skill() during hatch Phase 2.5.
    Consumed by AHCoreAgent.__init__ to enable/disable bricks.
    """

    loop_engine: LoopKind = LoopKind.CONVERSATION

    # Optional bricks — None means "not needed, use null stub"
    capbus: bool = True
    sandbox: SandboxTier = SandboxTier.STANDARD
    hooks: bool = True
    guard: Any = None           # OutputGuard instance or None
    credential_vault: bool = False
    file_processor: bool = False

    # Archetype metadata
    archetype: str = "multi-step"  # SkillArchetype value as string
    archetype_confidence: float = 1.0

    # v0.7: guard_active — skip OutputGuard.validate() for prompt-only skills
    guard_active: bool = False

    # v0.7.6: memory — enable persistent MemoryBrick (default-on, opt-out)
    memory: bool = True
