"""PlanLayer — State machine + structured planning for agenthatch agents.

v0.9.8: Implements the PLAN_GUIDED loop engine.  Agents running in plan_guided
mode first generate a structured plan (via a virtual `plan` tool), then execute
steps with explicit state tracking, repurposing detection, and verification.

Design decisions:
- Plan is generated by the LLM via a `plan` tool call at session start
- State transitions are managed by the loop, not the LLM
- Steps are linear (no DAG) — sufficient for most single-agent tasks
- Repurposing is triggered by consecutive tool failures or step blockage
- Lightweight (~250 lines) — no sub-agent delegation or token budgets
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Agent State Machine
# ---------------------------------------------------------------------------

class AgentState(str, Enum):
    """States an agent can be in during plan-guided execution."""

    STARTING = "starting"       # Initial state, waiting for plan
    PLANNING = "planning"       # Agent is generating/updating the plan
    EXECUTING = "executing"     # Agent is executing plan steps
    VERIFYING = "verifying"     # Agent is checking results
    REPLANNING = "replanning"   # Agent encountered a blockage, revising plan
    DONE = "done"               # Terminal state — all steps completed


# ---------------------------------------------------------------------------
# PlanStep
# ---------------------------------------------------------------------------

class PlanStep(BaseModel):
    """A single step in a structured plan."""

    step_id: int = 0
    description: str = ""
    tool_hint: str | None = None   # Recommended tool name (optional)
    status: str = "pending"         # pending | running | done | blocked
    result_summary: str = ""        # Brief outcome after step completes


# ---------------------------------------------------------------------------
# StructuredPlan
# ---------------------------------------------------------------------------

class StructuredPlan(BaseModel):
    """A complete structured plan with multiple steps."""

    goal: str = ""                  # One-sentence goal description
    steps: list[PlanStep] = Field(default_factory=list)
    current_step_index: int = 0     # Index of the currently executing step
    created_at: str = ""
    updated_at: str = ""

    @property
    def current_step(self) -> PlanStep | None:
        if 0 <= self.current_step_index < len(self.steps):
            return self.steps[self.current_step_index]
        return None

    @property
    def total_steps(self) -> int:
        return len(self.steps)

    @property
    def completed_steps(self) -> int:
        return sum(1 for s in self.steps if s.status == "done")

    @property
    def blocked_steps(self) -> int:
        return sum(1 for s in self.steps if s.status == "blocked")

    @property
    def is_complete(self) -> bool:
        return all(s.status == "done" for s in self.steps)

    def to_context_text(self) -> str:
        """Render the plan as text for system prompt injection."""
        lines = [f"## Plan: {self.goal}"]
        for step in self.steps:
            marker = {
                "pending": "☐",
                "running": "▶",
                "done": "✓",
                "blocked": "✗",
            }.get(step.status, "?")
            line = f"  {marker} Step {step.step_id}: {step.description}"
            if step.result_summary:
                line += f" — {step.result_summary}"
            lines.append(line)
        lines.append(f"Progress: {self.completed_steps}/{self.total_steps} steps done")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Plan tool definition (for CapBus)
# ---------------------------------------------------------------------------

PLAN_TOOL_DEFINITION = {
    "type": "function",
    "function": {
        "name": "plan",
        "description": (
            "Set or update the execution plan. Use this at the start of a "
            "complex task to break it into ordered steps. Re-call to update "
            "the plan when you discover new information or encounter blockers."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["set", "update", "complete"],
                    "description": (
                        "'set' creates a new plan, 'update' modifies it, "
                        "'complete' marks all steps done."
                    ),
                },
                "goal": {
                    "type": "string",
                    "description": "One-sentence description of the overall goal.",
                },
                "steps": {
                    "type": "array",
                    "description": "Ordered list of steps to execute.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "step_id": {
                                "type": "integer",
                                "description": "Step number (1-based).",
                            },
                            "description": {
                                "type": "string",
                                "description": "What to do in this step.",
                            },
                            "tool_hint": {
                                "type": "string",
                                "description": "Optional recommended tool name.",
                            },
                        },
                        "required": ["step_id", "description"],
                    },
                },
                "current_step_index": {
                    "type": "integer",
                    "description": "Index of the step currently being executed.",
                },
            },
            "required": ["action"],
        },
    },
}


# ---------------------------------------------------------------------------
# PlanLayer
# ---------------------------------------------------------------------------

class PlanLayer:
    """Manages the planning state machine for a single agent session.

    Usage:
        plan_layer = PlanLayer()
        # Inject plan tool into CapBus
        capbus.register_virtual_tool("plan", PLAN_TOOL_DEFINITION)
        # In conversation loop:
        plan_layer.handle_turn_start(context_mgr)
        response = llm.chat(...)
        plan_layer.handle_turn_end(response, context_mgr)
        if plan_layer.next_suggestion:
            messages.append({"role": "user", "content": plan_layer.next_suggestion})
    """

    # v0.9.8: repurposing triggers — maximum consecutive tool failures
    # before transitioning to REPLANNING.
    MAX_CONSECUTIVE_FAILURES = 3
    # v0.9.8: verification threshold — after this many steps complete,
    # suggest the agent verify before continuing.
    VERIFY_EVERY_N_STEPS = 5

    def __init__(self, mode: str = "conversation") -> None:
        self.state: AgentState = AgentState.STARTING
        self.plan: StructuredPlan = StructuredPlan()
        self._consecutive_tool_failures: int = 0
        self._turn_count: int = 0
        self._last_tool_success: bool = False
        # 'conversation' = plan tool available, minimal nagging
        # 'plan_guided' = plan tool available, more proactive planning hints
        self._mode: str = mode

    # -- State API -----------------------------------------------------------

    @property
    def plan_context(self) -> str:
        """Get the plan context text for system prompt injection.

        v0.9.8: Only nags about planning in early turns.  After turn 3,
        respects the agent's decision not to plan and stays quiet.
        When a plan exists, always shows full plan context.
        """
        # If a plan exists, always show it — the agent needs to track progress
        if self.plan.steps:
            ctx = self.plan.to_context_text()
            ctx += f"\nState: {self.state.value}\n"

            if self.state == AgentState.EXECUTING and self.plan.current_step:
                ctx += (
                    f"\nCurrent step: Step {self.plan.current_step.step_id}: "
                    f"{self.plan.current_step.description}"
                )

            if self.state == AgentState.REPLANNING:
                ctx += (
                    "\nYou are in REPLANNING mode.  A step was blocked.  "
                    "Use the `plan` tool to update the plan, then retry."
                )

            return ctx

        # No plan yet — only suggest in early turns, then stay quiet.
        # plan_guided mode nags a bit longer than conversation mode.
        nag_limit = 4 if self._mode == "plan_guided" else 2
        if self._turn_count <= nag_limit:
            return (
                "\n## Complex Task? Use a Plan\n"
                "If this task requires multiple coordinated steps, "
                "use the `plan` tool to break it down into ordered steps.  "
                "For simple single-step tasks, execute directly — no "
                "plan is needed."
            )

        # Turn 3+: agent chose not to plan, respect that decision
        return ""

    @property
    def next_suggestion(self) -> str | None:
        """Return a suggestion for what the agent should do next.

        Returns None if the agent doesn't need prompting.

        v0.9.8: Only nags STARTING once (turn 1).  PLANNING nags once.
        After that, lets the agent work naturally.
        """
        if self.state == AgentState.STARTING and self._turn_count <= 1:
            return (
                "This task may benefit from a structured plan. "
                "Use the `plan` tool to break it into steps before executing."
            )

        if self.state == AgentState.PLANNING and self._turn_count <= 2:
            return (
                "Use the `plan` tool to create a structured plan, "
                "then begin executing the first step."
            )

        if self.state == AgentState.REPLANNING:
            return (
                "The previous approach was blocked. "
                "Use the `plan` tool to update the plan with a new strategy."
            )

        if self.state == AgentState.VERIFYING:
            return (
                "You have completed several steps. "
                "Verify the results so far before continuing. "
                "If satisfied, mark the remaining steps. "
                "If issues found, use the `plan` tool to update."
            )

        return None

    # -- Core methods --------------------------------------------------------

    def handle_turn_start(self) -> None:
        """Called at the beginning of each conversation turn."""
        self._turn_count += 1

        # Check if we should suggest verification
        if (
            self.state == AgentState.EXECUTING
            and self.plan.completed_steps > 0
            and self.plan.completed_steps % self.VERIFY_EVERY_N_STEPS == 0
        ):
            self.state = AgentState.VERIFYING

    def handle_turn_end(
        self,
        response_text: str | None,
        tool_calls: list[dict[str, Any]] | None = None,
        tool_results: list[dict[str, Any]] | None = None,
    ) -> None:
        """Called after each LLM response to update state."""
        if tool_calls:
            self._process_tool_calls(tool_calls)
        elif tool_results:
            self._process_tool_results(tool_results)

    def handle_plan_tool(self, arguments: dict[str, Any]) -> str:
        """Process a `plan` tool call. Returns a status message."""
        action = arguments.get("action", "set")
        goal = arguments.get("goal", "")
        steps_data = arguments.get("steps", [])
        current_idx = arguments.get("current_step_index", 0)

        if action == "complete":
            for step in self.plan.steps:
                step.status = "done"
            self.plan.updated_at = datetime.now().isoformat()
            self.state = AgentState.DONE
            return "All steps marked complete. Task finished."

        if action in ("set", "update"):
            now = datetime.now().isoformat()
            self.plan.goal = goal or self.plan.goal

            if steps_data:
                new_steps: list[PlanStep] = []
                for i, s in enumerate(steps_data):
                    # Support both dict and PlanStep inputs
                    if isinstance(s, dict):
                        new_steps.append(PlanStep(
                            step_id=s.get("step_id", i + 1),
                            description=s.get("description", ""),
                            tool_hint=s.get("tool_hint"),
                            status="pending",
                        ))
                    elif isinstance(s, PlanStep):
                        new_steps.append(s)
                self.plan.steps = new_steps
                self.plan.current_step_index = current_idx

            self.plan.updated_at = now
            if not self.plan.created_at:
                self.plan.created_at = now

            if self.state in (AgentState.STARTING, AgentState.PLANNING):
                self.state = AgentState.EXECUTING
            elif self.state == AgentState.REPLANNING:
                self.state = AgentState.EXECUTING
                self._consecutive_tool_failures = 0

            step_count = len(self.plan.steps)
            return f"Plan {'created' if action == 'set' else 'updated'}. {step_count} steps. Begin execution at step {current_idx + 1}."

        return f"Unknown plan action: {action}"

    def advance_step(self, step_id: int, result: str = "") -> None:
        """Mark a step as done and advance to the next."""
        for step in self.plan.steps:
            if step.step_id == step_id:
                step.status = "done"
                step.result_summary = result
                break

        # Advance to next pending step
        for i, step in enumerate(self.plan.steps):
            if step.status == "pending":
                self.plan.current_step_index = i
                self.state = AgentState.EXECUTING
                return

        # All steps done
        self.state = AgentState.DONE

    def block_step(self, step_id: int, reason: str = "") -> None:
        """Mark a step as blocked and trigger repurposing."""
        for step in self.plan.steps:
            if step.step_id == step_id:
                step.status = "blocked"
                step.result_summary = reason
                break
        self.state = AgentState.REPLANNING

    # -- Internal ------------------------------------------------------------

    def _process_tool_calls(self, tool_calls: list[dict[str, Any]]) -> None:
        """Track tool calls for failure detection."""
        # We'll know about failures/successes in _process_tool_results
        pass

    def _process_tool_results(self, tool_results: list[dict[str, Any]]) -> None:
        """Process tool results to detect failures and blockages."""
        any_failure = False
        for result in tool_results:
            content = str(result.get("content", "") or "")
            tool_name = result.get("name", "unknown")

            # Detect tool execution failures
            failure_indicators = [
                "error", "Error", "ERROR",
                "failed", "Failed", "FAILED",
                "exception", "Exception",
                "traceback", "Traceback",
                "cannot", "Cannot",
                "unable to", "Unable to",
            ]
            is_failure = any(ind in content for ind in failure_indicators)

            if is_failure:
                any_failure = True
                logger.debug(
                    "PlanLayer: detected failure in tool %s (len=%d): %s",
                    tool_name, len(content), content[:100],
                )

            # Track success for the current step's tool
            if not is_failure and self.plan.current_step:
                tip = self.plan.current_step.tool_hint
                if tip and tip in tool_name:
                    self._last_tool_success = True

        if any_failure:
            self._consecutive_tool_failures += 1
            self._last_tool_success = False
            if self._consecutive_tool_failures >= self.MAX_CONSECUTIVE_FAILURES:
                if self.state == AgentState.EXECUTING:
                    logger.warning(
                        "PlanLayer: %d consecutive failures, "
                        "transitioning to REPLANNING",
                        self._consecutive_tool_failures,
                    )
                    self.state = AgentState.REPLANNING
        else:
            self._consecutive_tool_failures = 0

    # -- Serialization -------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Serialize plan layer state for checkpoint/offload."""
        return {
            "state": self.state.value,
            "plan": self.plan.model_dump(),
            "consecutive_tool_failures": self._consecutive_tool_failures,
            "turn_count": self._turn_count,
        }

    def get_plan_context(self) -> str:
        """Alias for plan_context — used by agent_loop.py."""
        return self.plan_context