"""agenthatch migrate — Convert old agenthatch.yaml to v0.6 format."""

from __future__ import annotations

import shutil
from datetime import datetime, timezone
from pathlib import Path

import typer
import yaml

from agenthatch.cli import console


def migrate_command(
    skill_dir: str = typer.Argument(..., help="Path to skill directory"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
) -> None:
    """Migrate agenthatch.yaml from v0.5 to v0.6 format.
    
    Extracts agent.runtime config to runtime.toml and cleans up agenthatch.yaml.
    """
    skill_path = Path(skill_dir).expanduser().resolve()
    ahs_path = skill_path / "agenthatch.yaml"
    
    if not ahs_path.exists():
        console.print(f"[red]No agenthatch.yaml found in {skill_path}[/red]")
        raise typer.Exit(code=1)
    
    raw = yaml.safe_load(ahs_path.read_text(encoding="utf-8"))
    
    agent_section = raw.get("agent", {})
    old_runtime = agent_section.get("runtime") if isinstance(agent_section, dict) else None
    
    if old_runtime is None:
        console.print("[yellow]No agent.runtime section found — already v0.6 format?[/yellow]")
        if not dry_run:
            # Still add status if missing
            if isinstance(agent_section, dict):
                agent_section["status"] = agent_section.get("status", "not_generated")
                raw["agent"] = agent_section
                _backup_and_write(ahs_path, raw)
        return
    
    # Extract runtime to runtime.toml
    runtime_toml = _build_runtime_toml(old_runtime)
    
    # Remove runtime from agent section
    agent_section.pop("runtime", None)
    agent_section["status"] = "not_generated"
    raw["agent"] = agent_section
    
    if dry_run:
        console.print("[yellow]Dry-run — would create:[/yellow]")
        console.print(f"  {skill_path / 'runtime.toml'}")
        console.print(runtime_toml)
        return
    
    # Backup original
    _backup_and_write(ahs_path, raw)
    
    # Write runtime.toml
    rt_path = skill_path / "runtime.toml"
    rt_path.write_text(runtime_toml, encoding="utf-8")
    
    console.print(f"[green]Migrated:[/green] {skill_path.name}")
    console.print(f"  agenthatch.yaml → v0.6 format (backup: .bak)")
    console.print(f"  runtime.toml created")
    console.print(f"  [dim]Next: agenthatch hatch {skill_dir} --force[/dim]")


def _backup_and_write(ahs_path: Path, data: dict) -> None:
    """Backup original and write new yaml."""
    bak_path = ahs_path.with_suffix(ahs_path.suffix + ".bak")
    shutil.copy2(ahs_path, bak_path)
    
    yaml_str = yaml.dump(data, allow_unicode=True, default_flow_style=False, sort_keys=False)
    ahs_path.write_text(yaml_str, encoding="utf-8")


def _build_runtime_toml(runtime: dict) -> str:
    """Build runtime.toml content from old agent.runtime config."""
    provider = runtime.get("provider", "openai")
    model = runtime.get("model", "gpt-4o")
    temperature = runtime.get("temperature", 0.7)
    max_tokens = runtime.get("max_tokens", 4096)
    
    # Determine env var name for api_key
    env_var_map = {"openai": "OPENAI_API_KEY", "deepseek": "DEEPSEEK_API_KEY", 
                   "anthropic": "ANTHROPIC_API_KEY", "ollama": ""}
    env_var = env_var_map.get(provider, "PROVIDER_API_KEY")
    api_key_line = f'api_key = "${{{env_var}}}"' if env_var else 'api_key = ""'
    
    lines = [
        f"# Runtime configuration for {provider}",
        f"# Generated by agenthatch migrate",
        "",
        "[llm]",
        f'provider = "{provider}"',
        f'model = "{model}"',
        api_key_line,
        f"temperature = {temperature}",
        f"max_tokens = {max_tokens}",
        "",
        "[compact]",
        "enabled = true",
        "threshold_tokens = 8000",
        "compact_ratio = 0.75",
    ]
    return "\n".join(lines) + "\n"